import type { ConfigKey, Resource } from '../types'

/*
 * config.toml as a single resource with TWO projections of the same data:
 *   - Settings: friendly forms, grouped by section
 *   - config.toml: the raw file, generated from these exact keys
 *
 * This is the answer to "why can't I see/edit config.toml in Studio?" — you can.
 * The file is the source of truth; the Settings form is a generated view of it.
 * Each key uses Danny's exact pseudocode shape.
 */

const keys: ConfigKey[] = [
  {
    key: 'project_id',
    label: 'Project ID',
    type: 'string',
    value: 'events-prod',
    default: 'events-prod',
    source: 'config.toml',
    requiresRestart: false,
    dangerous: false,
    planAvailability: ['free', 'pro', 'team', 'enterprise'],
    docsPath: '/docs/guides/local-development/cli/config#project_id',
    description: 'A unique reference for the project, used to scope generated artifacts.',
  },
  {
    key: 'api.port',
    label: 'API port',
    type: 'number',
    value: 54321,
    default: 54321,
    source: 'config.toml',
    requiresRestart: true,
    dangerous: false,
    planAvailability: ['free', 'pro', 'team', 'enterprise'],
    docsPath: '/docs/guides/local-development/cli/config#api.port',
    description: 'Port the REST and GraphQL API are served on.',
  },
  {
    key: 'api.max_rows',
    label: 'Max rows',
    type: 'number',
    value: 1000,
    default: 1000,
    source: 'config.toml',
    requiresRestart: false,
    dangerous: false,
    planAvailability: ['free', 'pro', 'team', 'enterprise'],
    docsPath: '/docs/guides/local-development/cli/config#api.max_rows',
    description: 'Maximum number of rows a single PostgREST request can return.',
  },
  {
    key: 'db.major_version',
    label: 'Postgres version',
    type: 'number',
    value: 15,
    default: 15,
    source: 'config.toml',
    requiresRestart: true,
    dangerous: true,
    planAvailability: ['free', 'pro', 'team', 'enterprise'],
    docsPath: '/docs/guides/local-development/cli/config#db.major_version',
    description: 'Major Postgres version. Changing this requires a full migration.',
  },
  {
    key: 'auth.site_url',
    label: 'Site URL',
    type: 'string',
    value: 'https://app.example.com',
    default: 'http://localhost:3000',
    source: 'config.toml',
    requiresRestart: false,
    dangerous: false,
    planAvailability: ['free', 'pro', 'team', 'enterprise'],
    docsPath: '/docs/guides/auth/redirect-urls',
    description: 'Base URL of your site, used for redirects and email links.',
  },
  {
    key: 'auth.jwt_expiry',
    label: 'JWT expiry',
    type: 'number',
    value: 3600,
    default: 3600,
    source: 'config.toml',
    requiresRestart: false,
    dangerous: false,
    planAvailability: ['free', 'pro', 'team', 'enterprise'],
    docsPath: '/docs/guides/auth/sessions',
    description: 'Lifetime of an access token in seconds.',
  },
  {
    key: 'auth.enable_signup',
    label: 'Allow new sign-ups',
    type: 'boolean',
    value: true,
    default: true,
    source: 'config.toml',
    requiresRestart: false,
    dangerous: false,
    planAvailability: ['free', 'pro', 'team', 'enterprise'],
    docsPath: '/docs/guides/auth',
    description: 'Whether new users may create an account.',
  },
  {
    key: 'auth.email.enable_confirmations',
    label: 'Confirm email',
    type: 'boolean',
    value: true,
    default: false,
    source: 'config.toml',
    requiresRestart: false,
    dangerous: false,
    planAvailability: ['free', 'pro', 'team', 'enterprise'],
    docsPath: '/docs/guides/auth/auth-email',
    description: 'Require users to confirm their email address before they can sign in.',
  },
  {
    key: 'auth.external.github.enabled',
    label: 'GitHub sign-in',
    type: 'boolean',
    value: true,
    default: false,
    source: 'config.toml',
    requiresRestart: false,
    dangerous: false,
    planAvailability: ['free', 'pro', 'team', 'enterprise'],
    docsPath: '/docs/guides/auth/social-login/auth-github',
    description: 'Enable the GitHub OAuth provider.',
  },
  {
    key: 'storage.file_size_limit',
    label: 'Global file size limit',
    type: 'string',
    value: '50MiB',
    default: '50MiB',
    source: 'config.toml',
    requiresRestart: true,
    dangerous: false,
    planAvailability: ['pro', 'team', 'enterprise'],
    docsPath: '/docs/guides/storage/uploads/file-limits',
    description: 'Maximum size for any single uploaded object across all buckets.',
  },
  {
    key: 'realtime.enabled',
    label: 'Realtime',
    type: 'boolean',
    value: true,
    default: true,
    source: 'config.toml',
    requiresRestart: true,
    dangerous: false,
    planAvailability: ['free', 'pro', 'team', 'enterprise'],
    docsPath: '/docs/guides/realtime',
    description: 'Serve database changes and broadcast over websockets.',
  },
]

export const configToml: Resource = {
  id: 'config.toml',
  kind: 'config-key',
  category: 'Config',
  name: 'config.toml',
  qualified: 'config.toml',
  description:
    'Project configuration — the source of truth. The Settings form below is a generated projection of this exact file.',
  docsUrl: 'https://supabase.com/docs/guides/local-development/cli/config',
  relations: [],
  actions: [
    {
      id: 'view-logs',
      label: 'View change history',
      kind: 'view-logs',
      description: 'Config is versioned — every change is a diff.',
    },
  ],
  data: { configGroup: keys },
  projections: [
    {
      type: 'config',
      label: 'Settings',
      renderer: 'KeyValuePanel',
      generated: true,
      hint: 'Forms generated from config.toml, grouped by section.',
    },
    {
      type: 'file',
      label: 'config.toml',
      renderer: 'KeyValuePanel',
      generated: true,
      hint: 'The raw file. Edit here or in Settings — same source of truth.',
    },
  ],
}
